### PR TITLE
Awating review

### PR DESCRIPTION
**Pull request by dustinsandiegoriver**

### CODE REVIEW

**Comment by mejiacsd** [comment]
Hey Dustin, what did you want to do?

**Comment by dustinsandiegoriver** [comment]
I’m working on the donate page and getting familiar with the desktop application. No changes have been made yet

**Comment by mejiacsd** [comment]
Gotcha. Im going to close this out then.

**Comment by dustinsandiegoriver** [comment]
Thanks I’ll follow up with an email once changes are submitted.

**Pull request closed without merging**
